### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by ccqedq** [BenniG123/icp-slam-prototype#1]
I have read your code and it is great. But I have some questions. Can you show me your master's thesis?

**Comment by BenniG123** [comment]
I'm glad you found this code helpful.  Here's my two cents - my SLAM implementation is incredibly basic and extremely lacking in flexibility and efficiency.  This repo can be helpful, if nothing else, just to have some implementations of computational geometry using OpenCV data types, and have a nice CMake solution that goes together.  If you do make any improvements or cleanup, feel free to submit a PR.

Here's the link:
https://lib.dr.iastate.edu/cgi/viewcontent.cgi?referer=https://www.bing.com/&httpsredir=1&article=6651&context=etd

**Comment by ccqedq** [comment]
I'm very grateful for your help. There are still some confusion I don't understand. From your code, the execution of ICP registration is completely calculated by the point cloud generated by the current and last depth frame, which seems to have nothing to do with the color image. But you used color images and fast features in your code, which is specificly in  your getTransformation function in  icp.cpp module,hope for your reply.
